export default {
  name: 'company',
  title: 'Company',
  type: 'document',
  fields: [
    { name: 'name', title: 'Name (ID)', type: 'string' },
    { name: 'nameEn', title: 'Name (EN)', type: 'string' },
    { name: 'description', title: 'Description (ID)', type: 'text' },
    { name: 'descriptionEn', title: 'Description (EN)', type: 'text' },
    { name: 'logo', title: 'Logo', type: 'image' },
    { name: 'about', title: 'About (ID)', type: 'text' },
    { name: 'aboutEn', title: 'About (EN)', type: 'text' },
    { name: 'vision', title: 'Vision (ID)', type: 'text' },
    { name: 'visionEn', title: 'Vision (EN)', type: 'text' },
    { name: 'mission', title: 'Mission (ID)', type: 'text' },
    { name: 'missionEn', title: 'Mission (EN)', type: 'text' },
    { name: 'address', title: 'Address (ID)', type: 'text' },
    { name: 'addressEn', title: 'Address (EN)', type: 'text' },
    { name: 'phone', title: 'Phone', type: 'string' },
    { name: 'email', title: 'Email', type: 'string' },
    { name: 'website', title: 'Website', type: 'url' },
    {
      name: 'socialMedia',
      title: 'Social Media',
      type: 'object',
      fields: [
        { name: 'facebook', title: 'Facebook', type: 'url' },
        { name: 'instagram', title: 'Instagram', type: 'url' },
        { name: 'twitter', title: 'Twitter', type: 'url' },
        { name: 'linkedin', title: 'LinkedIn', type: 'url' },
      ],
    },
  ],
}